# Generated by Django 4.1.3 on 2022-11-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutra_app', '0002_fruitclassifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fdc_id', models.IntegerField()),
                ('food_class', models.CharField(blank=True, default='', max_length=255)),
                ('data_type', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('food_category_id', models.IntegerField(blank=True, default=0)),
                ('publication_date', models.DateField(blank=True, default='')),
                ('scientific_name', models.CharField(blank=True, default='', max_length=255)),
                ('food_key', models.CharField(blank=True, default='', max_length=255)),
                ('is_having_nutrient_id', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCalorieConversionFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_nutrient_conversion_factor_id', models.IntegerField(blank=True, default=0)),
                ('protein_value', models.FloatField(blank=True)),
                ('fat_value', models.FloatField(blank=True)),
                ('carbohydrate_value', models.FloatField(blank=True)),
                ('calories', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrientConversionFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_nutrient_conversion_factor_id', models.IntegerField(blank=True)),
                ('fdc_id', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodProtienConversionFactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('food_nutrient_conversion_factor_id', models.IntegerField(blank=True)),
                ('value', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FoodUpdateLogEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fdc_id', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True, default='')),
                ('last_updated', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('measure_unit_id', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('abbreviation', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nutrient_id', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('unit_name', models.CharField(blank=True, default='', max_length=10)),
                ('nutrient_nbr', models.IntegerField(blank=True, unique=True)),
                ('rank', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientIncomingName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nutrient_incoming_name_id', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('nutrient_id', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
